[workspace]
members = [
  "crates/*",
  "xtask"
]
default-members = ["crates/*"]
resolver = "2"

[profile.release]
lto = true

[workspace.package]
version = "0.44.0"
authors = ["Herrington Darkholme <2883231+HerringtonDarkholme@users.noreply.github.com>"]
edition = "2024"
license = "MIT"
documentation = "https://github.com/hyper-light/vorpal"
homepage = "https://github.com/hyper-light/vorpal"
repository = "https://github.com/hyper-light/vorpal"
rust-version = "1.85"
readme = "README.md"

[workspace.dependencies]
vorpal-core = { path = "crates/core", version = "0.44.0", default-features = false }
vorpal-canonical = { path = "crates/canonical", version = "0.44.0" }
vorpal-config = { path = "crates/config", version = "0.44.0" }
vorpal-dynamic = { path = "crates/dynamic", version = "0.44.0" }
vorpal-graph = { path = "crates/graph", version = "0.44.0" }
vorpal-index = { path = "crates/index", version = "0.44.0" }
vorpal-ingest = { path = "crates/ingest", version = "0.44.0" }
vorpal-kg = { path = "crates/kg", version = "0.44.0" }
vorpal-language = { path = "crates/language", version = "0.44.0" }
vorpal-lsp = { path = "crates/lsp", version = "0.44.0" }
vorpal-mem = { path = "crates/mem", version = "0.44.0" }
vorpal-outline = { path = "crates/outline", version = "0.44.0" }
vorpal-resolve = { path = "crates/resolve", version = "0.44.0" }
vorpal-segment = { path = "crates/segment", version = "0.44.0" }

bit-set = { version = "0.10.0" }
ignore = { version = "0.4.22" }
regex = { version = "1.10.4" }
serde = { version = "1.0.200", features = ["derive"] }
serde_regex = "1.2.0"
serde_yaml = "0.9.33"
tree-sitter = { version = "0.26.3" }
thiserror = "2.0.0"
schemars = "1.0.0"
anyhow = "1.0.82"
dashmap = "6.0.0"
