//! The language matrix (IMPROVEMENTS #10): parser support, outline support, reference
//! extraction, and measured relation precision are SEPARATE claims — this test generates
//! `docs/LANGUAGES.md` from code truth and keeps it current (self-healing, like the schema
//! docs: a divergence rewrites the file; the diff then belongs to the commit that caused it).
//!
//! Column truth sources:
//! - **Parser**: every `SupportLang` compiles a vendored parser, and every parser's upstream
//!   corpus runs in `grammar_corpus.rs` — so this column is uniform and corpus-gated.
//! - **Outline rules**: `crates/outline/src/default_rules/<lang>.yml` presence.
//! - **Reference extraction**: `vorpal_ingest::has_reference_extraction` (code truth).
//! - **Relation precision**: the languages whose resolution outcomes are exhaustively
//!   labelled in `crates/index/tests/resolution_eval.rs` (parsed from that source, so adding
//!   a fixture updates the matrix automatically).

use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use vorpal_ingest::{SupportLang, has_reference_extraction};

fn repo_root() -> PathBuf {
  Path::new(env!("CARGO_MANIFEST_DIR"))
    .join("../..")
    .canonicalize()
    .unwrap()
}

/// The default outline-rule file a language uses (Tsx shares the TypeScript rules).
fn outline_rule_name(lang: SupportLang) -> String {
  match lang {
    SupportLang::Tsx => "typescript".to_string(),
    SupportLang::CSharp => "csharp".to_string(),
    other => format!("{other:?}").to_lowercase(),
  }
}

/// Languages with exhaustively labelled resolution fixtures, read from the eval source.
fn labelled_languages() -> BTreeSet<String> {
  let source = fs::read_to_string(repo_root().join("crates/index/tests/resolution_eval.rs"))
    .expect("resolution_eval.rs");
  let mut langs = BTreeSet::new();
  for line in source.lines() {
    let trimmed = line.trim();
    if let Some(rest) = trimmed.strip_prefix("lang: \"") {
      if let Some(lang) = rest.split('"').next() {
        langs.insert(lang.to_string());
      }
    }
  }
  langs
}

/// The eval fixture's name for a language ("cpp", "typescript", …).
fn eval_name(lang: SupportLang) -> String {
  format!("{lang:?}").to_lowercase()
}

#[test]
fn language_matrix_is_generated_from_code_truth() {
  let root = repo_root();
  let labelled = labelled_languages();
  assert!(
    !labelled.is_empty(),
    "no labelled languages parsed from resolution_eval.rs — did its fixture shape change?"
  );

  let mut rows = String::new();
  for &lang in SupportLang::all_langs() {
    let outline = root
      .join("crates/outline/src/default_rules")
      .join(format!("{}.yml", outline_rule_name(lang)));
    assert!(
      outline.is_file(),
      "{lang:?}: no outline rules at {} — every supported language ships outline rules",
      outline.display()
    );
    let extraction = has_reference_extraction(lang);
    let precision = if labelled.contains(&eval_name(lang)) {
      "labelled-gated (precision = recall = 1.0)"
    } else if extraction {
      "extracted; not fixture-gated"
    } else {
      "—"
    };
    let extraction_cell = if extraction {
      "✓"
    } else {
      "— (structural only)"
    };
    rows.push_str(&format!(
      "| {lang:?} | ✓ corpus-gated | ✓ | {extraction_cell} | {precision} |\n"
    ));
  }

  let doc = format!(
    "# Language support matrix\n\n\
     Generated by `crates/ingest/tests/language_matrix.rs` — do not edit by hand; the test\n\
     rewrites this file from code truth and fails only when the truth sources are broken.\n\n\
     The four columns are **separate claims** (IMPROVEMENTS #10): a compiled parser does not\n\
     imply outline rules; outline rules do not imply call/import extraction; extraction does\n\
     not imply measured resolution precision. Precision is *labelled-gated* only where\n\
     `crates/index/tests/resolution_eval.rs` carries an exhaustively labelled fixture whose\n\
     precision and recall must both be 1.0.\n\n\
     | Language | Parser | Outline rules | Reference extraction | Relation precision |\n\
     |---|---|---|---|---|\n\
     {rows}\n\
     **Parser**: vendored at a pinned, digest-verified commit (`grammars/PROVENANCE.json`)\n\
     and exercised by its upstream corpus (`grammar_corpus.rs`, 4k+ tests).\n\
     **Outline rules**: `crates/outline/src/default_rules/`. **Reference extraction**:\n\
     `vorpal_ingest::has_reference_extraction` — structural-only languages have no\n\
     call/import semantics to extract. **Relation precision**: the labelled resolution\n\
     harness; `extracted; not fixture-gated` means edges exist with honest grades but no\n\
     exhaustive per-language label set yet.\n"
  );

  let path = root.join("docs/LANGUAGES.md");
  let current = fs::read_to_string(&path).unwrap_or_default();
  if current != doc {
    fs::write(&path, &doc).unwrap();
    println!("rewrote docs/LANGUAGES.md from code truth");
  }
  assert_eq!(fs::read_to_string(&path).unwrap(), doc);
}
