from typing import Any, List, Optional, Tuple, overload, Unpack, Dict

from . import Rule, Config, CustomLang

class Pos:
    line: int
    column: int
    index: int

class Range:
    start: Pos
    end: Pos

class Edit:
    start_pos: int
    end_pos: int
    inserted_text: str

class SgRoot:
    def __init__(self, src: str, language: str) -> None: ...
    def root(self) -> SgNode: ...
    def filename(self) -> str: ...

class SgNode:
    # Node Inspection
    def range(self) -> Range: ...
    def is_leaf(self) -> bool: ...
    def is_named(self) -> bool: ...
    def is_named_leaf(self) -> bool: ...
    def kind(self) -> str: ...
    def text(self) -> str: ...

    # Refinement
    def matches(self, **rule: Unpack[Rule]) -> bool: ...
    def inside(self, **rule: Unpack[Rule]) -> bool: ...
    def has(self, **rule: Unpack[Rule]) -> bool: ...
    def precedes(self, **rule: Unpack[Rule]) -> bool: ...
    def follows(self, **rule: Unpack[Rule]) -> bool: ...
    def get_match(self, meta_var: str) -> Optional[SgNode]: ...
    def get_multiple_matches(self, meta_var: str) -> List[SgNode]: ...
    def get_transformed(self, meta_var: str) -> Optional[str]: ...
    def __getitem__(self, meta_var: str) -> SgNode: ...

    # Search
    @overload
    def find(self, config: Config) -> Optional[SgNode]: ...
    @overload
    def find(self, **kwargs: Unpack[Rule]) -> Optional[SgNode]: ...
    @overload
    def find_all(self, config: Config) -> List[SgNode]: ...
    @overload
    def find_all(self, **kwargs: Unpack[Rule]) -> List[SgNode]: ...

    # Tree Traversal
    def get_root(self) -> SgRoot: ...
    def field(self, name: str) -> Optional[SgNode]: ...
    def field_children(self, name: str) -> List[SgNode]: ...
    def parent(self) -> Optional[SgNode]: ...
    def child(self, nth: int) -> Optional[SgNode]: ...
    def children(self) -> List[SgNode]: ...
    def ancestors(self) -> List[SgNode]: ...
    def next(self) -> Optional[SgNode]: ...
    def next_all(self) -> List[SgNode]: ...
    def prev(self) -> Optional[SgNode]: ...
    def prev_all(self) -> List[SgNode]: ...

    # Edit
    def replace(self, new_text: str) -> Edit: ...
    def commit_edits(self, edits: List[Edit]) -> str: ...

def register_dynamic_language(langs: Dict[str, CustomLang]): ...

# ── Repository intelligence (index / graph / search) ─────────────────────────
# Typed complements to the structural API above: build a knowledge-graph index,
# query relations with resolution grades, and run hybrid search. Record-returning
# methods yield plain dicts/lists (the pythonized vorpal-index typed records).

class NodeInfo:
    id: int
    name: str
    kind: str
    path: str
    signature: str
    exported: bool
    span: Tuple[int, int]

class BuildReport:
    indexed: int
    skipped: int
    nodes: int
    resolved: int
    ambiguous: int
    external: int
    masked: int
    reused: bool

class Index:
    @staticmethod
    def open(index_dir: str) -> Index: ...
    @property
    def generation(self) -> str: ...
    def node(self, id: int) -> Optional[Dict[str, Any]]: ...
    def nodes(
        self,
        name: str,
        path: Optional[str] = None,
        kind: Optional[str] = None,
        id: Optional[int] = None,
        all: bool = False,
    ) -> List[Dict[str, Any]]: ...
    def related(
        self,
        verb: str,
        name: str,
        path: Optional[str] = None,
        kind: Optional[str] = None,
        id: Optional[int] = None,
        all: bool = False,
    ) -> List[Dict[str, Any]]: ...
    def reachable(
        self,
        name: str,
        direction: str,
        relations: Optional[List[str]] = None,
        max_depth: Optional[int] = None,
        min_grade: Optional[str] = None,
        path: Optional[str] = None,
        kind: Optional[str] = None,
        id: Optional[int] = None,
        all: bool = False,
    ) -> List[Dict[str, Any]]: ...
    def why(
        self,
        from_id: int,
        to_id: Optional[int] = None,
        name: Optional[str] = None,
    ) -> Dict[str, Any]: ...
    def search(
        self,
        query: str,
        k: int = 10,
        path: Optional[str] = None,
        prefix: Optional[str] = None,
        kind: Optional[str] = None,
        lang: Optional[str] = None,
        exported: bool = False,
    ) -> List[Dict[str, Any]]: ...

def index_build(src: str, out: Optional[str] = None) -> str: ...
def index_build_report(src: str, out: Optional[str] = None) -> BuildReport: ...
def index_search(index_dir: str, query: str, k: int = 10, explain: bool = False) -> str: ...
def index_graph(
    index_dir: str,
    verb: str,
    name: str,
    path: Optional[str] = None,
    kind: Optional[str] = None,
    id: Optional[int] = None,
    all: bool = False,
    ids: bool = False,
) -> str: ...
def index_node(index_dir: str, id: int) -> NodeInfo: ...
